#include <iostream>

using namespace std;

int main()
{
    try
    {
	// do something
    }
    catch(logic_error& ex)
    {
    }
    catch(invalid_argument& ex)
    {
    }
}
